version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    environment:
      - discovery.type=single-node
      - logger.level=WARN
    ports:
      - 9200:9200
    networks:
      - mynetwork

  es_setup:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./es_setup.py:/app/es_setup.py
    command: ["python", "es_setup.py"]
    networks:
      - mynetwork
    depends_on:
      - elasticsearch

  search_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app.py:/app/app.py
    command: ["python", "app.py"]
    ports:
      - 5000:5000
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - DEBUG=TRUE
      - logger.level=INFO
    networks:
      - mynetwork
    depends_on:
      - elasticsearch

networks:
  mynetwork:
    driver: bridge
